#!/bin/bash
# Author: Paulo Jeronimo (email: paulojeronimo@gmail.com, twitter: @paulojeronimo)

source config

GITHUB_SISLEGIS_DOTFILES=http://github.com/$GITHUB_USER/sislegis-dotfiles
GITHUB_SISLEGIS_AMBIENTE=http://github.com/$GITHUB_USER/sislegis-ambiente
INSTALL_DIR=.github.com/$GITHUB_USER
X_INSTALADO=false

sudo sed -i '
  s/^\(%wheel.*ALL\)/#\1/
  s/^# \(%wheel.*NOPASSWD.*\)/\1/
' /etc/sudoers

sudo useradd -m -s /bin/bash -G wheel sislegis &> /dev/null || {
    echo "Falha ao criar usuário sislegis."
    echo "O ambiente já não está instalado?"
    exit 1; 
}

type xhost &> /dev/null && X_INSTALADO=true

$X_INSTALADO && {
    cmd="xhost +si:localuser:sislegis"; $cmd
    f=~/.bashrc; grep -q "xhost.*sislegis" $f || echo "$cmd" >> $f
}

sudo -u sislegis bash <<EOF
$X_INSTALADO && echo 'export DISPLAY=:0' >> ~/.bashrc
sudo yum -y install tar unzip wget
curl -sSL https://satya164.github.io/fedy/fedy-installer | sudo bash
sudo fedy -e oracle_jdk
cd && mkdir -p $INSTALL_DIR && cd $INSTALL_DIR
git clone $GITHUB_SISLEGIS_DOTFILES
${GITHUB_SISLEGIS_DOTFILES##*/}/install
EOF

cat <<EOF | sudo -u sislegis bash -c 'cat - > ~/.github'
GITHUB_USER=$GITHUB_USER
GITHUB_NAME='$GITHUB_NAME'
GITHUB_EMAIL=$GITHUB_EMAIL
EOF

sudo -u sislegis bash <<EOF
cd ~/$INSTALL_DIR
$BAIXA_INSTALADORES || { 
    echo "export INSTALA_OPCS='--nao-baixa-instaladores'" >> ~/.bashrc
    source ~/.bashrc
}
git clone $GITHUB_SISLEGIS_AMBIENTE
EOF

[ -d "sislegis" ] && {
    [ "`sudo stat -c %u sislegis/home/sislegis`" != "`sudo id -u sislegis`" ] && \
    sudo chown -R sislegis: sislegis/home/sislegis
    ./restaurar
}

sudo -u sislegis bash <<EOF
cd ~/$INSTALL_DIR
${GITHUB_SISLEGIS_AMBIENTE##*/}/instalar
EOF

# vim: set ts=4 sw=4 expandtab:
